### ISSUE TITLE
hdr picture differs between cli version 2.4.0-8 and 2.5.0-1

### ISSUE THREAD

**Issue by biokomiker** [LuminanceHDR/LuminanceHDR#56]
Thank you for this nice piece of software and its continuing improvement. I have a work-flow using command line. I observed that the ldrs have less colour with the new version. I could trace this back to the hdr creation of both versions. The hdrs differs between the versions. There is also a difference in file size in the underlying hdrs.

For initial hdr creation I use:

luminance-hdr-cli -a AIS -s $outputfile_base".hdr"  $inputfiles

Any explanation for that? Are different default values used in both versions?

**Comment by biokomiker** [comment]
Here some ldrs (cropped) generated through cli from hdrs generated by the two versions.

As the cli syntax has changed the commands are different, but the root are the differences in the hdrs.

luminance-hdr-cli -l $outputfile_base".hdr" -t fattal --gamma 0.9 -o $outputfile_base"_fattal.jpg" (v.2.4)

luminance-hdr-cli -l $outputfile_base".hdr" --tmo fattal --gamma 0.9 -o $outputfile_base"_fattal.jpg" (v.2.5)

The differences are clearly visible.
![version2 5_cropped](https://cloud.githubusercontent.com/assets/20150288/25773968/7cfe774c-3287-11e7-861b-769cc4d4f93a.jpg)
![version2 4_cropped](https://cloud.githubusercontent.com/assets/20150288/25773969/7cfffc3e-3287-11e7-8f99-d60f5d97d841.jpg)

**Comment by fcomida** [comment]
A lot of issues have been discovered and fixed in hdr creation since 2.5.0. v2.5.1 will be out very soon, hopefully in just few days. Since you are on Linux, why don't you try compiling yourself latest git snapshot? This way you can confirm all issues are now gone.

**Comment by biokomiker** [comment]
Sorry, I did not see the recent changelog. Compiling is not my field of experience, I will wait and test 2.5.1. Thanks !

**Comment by fcomida** [comment]
I asked you because compiling LHDR on Linux is pretty straightforward, after you set up the building environment with a bit of effort (only the first time) it's just a matter of running `git pull` and `make`. We are ready for 2.5.1 anyway,  preparing the **Windows** and **OS X** installers...

**Comment by fcomida** [comment]
![test-2 4 0](https://cloud.githubusercontent.com/assets/11018726/26196754/2c568acc-3bc0-11e7-9cb5-8f1a251f7dbe.jpg)
Fattal 2.4.0: beta = 0.78 gamma=1.2
![test-2 5 1](https://cloud.githubusercontent.com/assets/11018726/26196755/2c58cc9c-3bc0-11e7-97c7-90aec0790d36.jpg)
Fattal 2.5.1: beta = 0.78 gamma=1.2

I confirm tonemapping output is the same for 2.4.0 and 2.5.1

**Comment by biokomiker** [comment]
Great - I will try it the weekend, Thanks,

**Comment by biokomiker** [comment]
Sorry does not work on my computer:


luminance-hdr-cli --version
Luminance HDR version 2.5.1 [Build ]

![version 2 51_cropped](https://cloud.githubusercontent.com/assets/20150288/26277661/4f5ddd72-3d8c-11e7-86c5-9f596600e2fe.jpg)

It is more similar to 2.5 than to 2.4 I would say. Making LDRs is ok with 2.5.1, since it yields the "same" LDRs  when starting from HDR made with 2.4.

Greetings

**Comment by fcomida** [comment]
@biokomiker The main problem is that 2.4.0 has a bug, linear response == gamma response so for comparing the two you must output an HDR using gamma response in both 2.4.0 and 2.5.1. There still are minor differences due to a different implentation of the merging algorithm though.

![test-2 4 0](https://cloud.githubusercontent.com/assets/11018726/26282617/05ab62b0-3e15-11e7-8494-e26078db07e4.jpg)
2.4.0 - gamma response
![test-2 5 1](https://cloud.githubusercontent.com/assets/11018726/26282618/05aff618-3e15-11e7-9bcd-7b4f1f167ea3.jpg)
2.5.1 - gamma response
![test-2 4 0-linear](https://cloud.githubusercontent.com/assets/11018726/26282676/3d148924-3e16-11e7-8990-9306715878fa.jpg)
2.4.0 - linear response
![test-2 5 1-linear](https://cloud.githubusercontent.com/assets/11018726/26282677/3d16cd92-3e16-11e7-82de-cb7e02e9bef0.jpg)
2.5.1 - linear response

**Comment by biokomiker** [comment]
Ok, with --hdrResponseCurve gamma version 2.5.1 now looks quite similar to previous 2.4.8.

Thanks for the explanations!
